### ISSUE TITLE
[Isssue] Can't comment on profile

### ISSUE THREAD

**Issue by olesiek** [despa1r1337/FSOCIETY-SERVICE-BOT#1] opened 2020-02-07 08:25 UTC
Hi, I can't sent any comments on my profile even if it's all set to  public.

**Comment by verdammnis** [comment] 2020-02-07 15:39
> Hi, I can't sent any comments on my profile even if it's all set to public.

have you spent $ 5 on your account?

**Comment by olesiek** [comment] 2020-02-07 17:00
Whops, Forgot about this. But I noticed that If user is  on my friendlist I can comment  him  without spending 5$,  so could you add community task to send friend request to  specified profile?

**Comment by verdammnis** [comment] 2020-02-07 17:17
> Whops, Forgot about this. But I noticed that If user is on my friendlist I can comment him without spending 5$, so could you add community task to send friend request to specified profile?


1) Steam system allows you to leave comments in the Steam friends.

2) the program is not mine, I can not add anything.

**Comment by verdammnis** [comment] 2020-02-07 17:52
if the problem is solved, close it

**Closed as completed** 2020-02-08 17:30 UTC
